version: '3'
services:
  restcomm_jss7:
    build:
      context: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
     - "3435:3435"
     - "8080:8080"
     - "8009:8009"
